insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(1001,'USD','INR',75,'');
insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(1002,'CAD','INR',50,'');